[package]
name = "parser"
version = "0.1.0"
edition = "2021"

[dependencies]
drop_bomb = "0.1.5"
lexer = {path = "../lexer"}
rowan = "0.10.0"
syntax = {path = "../syntax"}
text-size = "1.0.0"

[dev-dependencies]
expect-test = "1.0.1"
